# Question To Myself

What if I have two movies and a bunch of participants rated those movies. Then I would have N x 2 matrix. 

Probably some people won’t have watched both of the movies, so some ratings will be missing. 
Now the column rank could be at most two, since we have only two columns, and therefore row rank is also at most 2.

If I select two independent rows, then I should be able to fill the gaps with linear approximation. Right ?

In [17]:
import numpy as np
import pandas as pd
from plotnine import *
from itertools import combinations

In [3]:
N = 50

np.random.seed(42)
df = pd.DataFrame(
    np.random.randint(1, 11, size = (N,2)), 
    columns= ['StarWars', 'Inception']
)

df.head()

   StarWars  Inception
0         7          4
1         8          5
2         7         10
3         3          7
4         8          5

Now with probability p, I will delete the entry in our matrix

In [11]:
p = 0.3

mask = np.random.rand(*df.shape) < p
df_nan = df.mask(mask)

df_nan.isna().sum()

StarWars     14
Inception    18
dtype: int64

Now we will find two linearly independent row vectors:

In [30]:
clean = df_nan.dropna() # we will drop the rows which contains a NaN

base1 = None
base2 = None

for i in combinations(clean.index, 2):
    v1 = clean.loc[i[0]]
    v2 = clean.loc[i[1]]

    determinant = v1[0]*v2[1] - v1[1] * v2[0]
    
    if determinant != 0:
        if base1 is None:
            base1 = [i[0], i[1]]
        elif base2 is None:
            base2 = [i[0], i[1]]
            break

/var/folders/nn/rd9y9hfx7qz4tk9cjwqs2xrh0000gn/T/ipykernel_72445/1874667018.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

Now we have 2 different bases for the range of rows

In [34]:
rows_with_one_nan = df_nan[df_nan.isna().sum(axis=1) == 1]
rows_with_one_nan.head()

   StarWars  Inception
2       7.0        NaN
3       3.0        NaN
6       NaN        3.0
7       6.0        NaN
9       NaN        2.0

# Base 1

we will get the inverse matrix of our base vectors

In [48]:
print(df.loc[base1[0], :])
print('--------------------')
print(df.loc[base1[1], :])
print('--------------------')
A = df.loc[[base1[0], base1[1]], :].to_numpy().T
print(A)

StarWars     7
Inception    4
Name: 0, dtype: int64
--------------------
StarWars     8
Inception    5
Name: 1, dtype: int64
--------------------
[[7 8]
 [4 5]]

In [50]:
np.linalg.inv(A)

array([[ 1.66666667, -2.66666667],
       [-1.33333333,  2.33333333]])

---------

At this point, I realized that the statement directly true ! LOLLLLLL

Since I have two independt vectors in 2 dimensional vector space, ofcourse I'm able to rewrite every vector as their linear combination. 
But the real issue is that I need a second component after all... 

Even if I take the inverse matrix consisting of 2 linearly independent vectors, then I get 

$$
\begin{bmatrix}

a & b \\

c & d

\end{bmatrix}

\begin{bmatrix}

e \\

*

\end{bmatrix}
$$

So I need the missing value after all, LolllllLllLLllL